import { useState, useEffect, createContext } from 'react'
import { useRouter } from 'next/router'
import SideNav from 'components/admin/adminSideNavbar'
import Head from 'next/head'

export const dataContext = createContext()

export default function AdminPage(){
    const [ isAdmin, setIsAdmin ] = useState(false)
    const router = useRouter()

    useEffect(() => {
        if(router.isReady){
            if(localStorage.getItem('jwt')){
                axios.get('/api/isAdmin', {
                    headers: { jwt: localStorage.getItem('jwt') }
                }).then(result => {
                    if(result.data.isAdmin){
                        setIsAdmin(true)
                    } else {
                        router.push({pathname: '/', query:{ } }, undefined,{ shallow: false } )
                        return
                    }
                }).catch(err => {
                    router.push({pathname: '/', query:{ } }, undefined,{ shallow: false } )
                    return
                })
            } else {
                router.push({pathname: '/', query:{ } }, undefined,{ shallow: false } )
                return
            }
        }
    }, [router])

    if(!isAdmin) {
        return (
          <div>
              <Head>
                  <title>Admin | PT Bookstore</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
              </Head>
              <div >
                  <main >
                      
                  </main>
              </div>
          </div>
        )
    } else {
        return (
            <div>
                <SideNav />
            </div>
        )
    }
}