import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import styles from './orders.module.css'
import Header from 'components/header'
import SideNavBar from 'components/user/sideNavbar'
import axios from 'axios'

export default function Orders() {
    const [ isLogin, setIsLogin ] = useState(false)
    const router = useRouter()


    useEffect(() => {
        if(localStorage.getItem('jwt')){
            setIsLogin(true)
            getData()
        } else {
            router.push({pathname: '/', query:{ } }, undefined,{ shallow: false } )
        }
    }, [])

    const getData = () => {
        const url = process.env.NEXT_PUBLIC_BACKEND + '/user/'
        axios.get(url, {
            headers: { jwt: localStorage.getItem('jwt')}
        })
        .then(result => {
            
        })
    }

    if(!isLogin) {
        return (
            <div>
                <Head>
                    <title>Orders | PT Bookstore</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header />
                <div className={styles.container}>
                    <main className={styles.main}>
                        
                    </main>
                </div>
            </div>
        )
    } else {
        return (
            <div>
                <Head>
                    <title>Orders | PT Bookstore</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header />
                <div className={styles.container}>
                    
                    <main className={styles.main}>
                        <SideNavBar />
                        <div className={styles.screen} >
                            <title>profile</title>
                            <center><h1 style={{fontSize: '30px'}}>รายการสั่งซื้อ</h1></center>
                            <div>

                            </div>
                        </div>
                    </main>
                </div>
            </div>
        )
    }
}