import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import styles from './orders.module.css'
import Header from 'components/header'
import SideNavBar from 'components/user/sideNavbar'
import axios from 'axios'
import Link from "next/link"

import { RiArrowDownSLine } from 'react-icons/ri'
import { IoIosArrowBack, IoIosArrowForward } from 'react-icons/io'

export default function Orders() {
    const [ isLogin, setIsLogin ] = useState(false)
    const router = useRouter()
    const [ orderList, setOrderList ]= useState([])
    const [ showDropdown, setShowDropdown ] = useState(false)
    const [ sort, setSort ] = useState({status: undefined, thai_status: undefined})
    const [ previousSort, setPreviousSort ] = useState({status: undefined, thai_status: undefined})
    const [ currentPages, setCurrentPages ] = useState(0)

    useEffect(() => {
        if(router.isReady){
            if(localStorage.getItem('jwt')){
                setIsLogin(true)
                getOrder()
            } else {
                return router.push({pathname: '/', query:{ } }, undefined,{ shallow: false } )
            }
            setCurrentPages(parseInt(router.query.pages) || 1)
            setStatusSort(router.query.sort || 'all')
        }
    }, [router])

    useEffect(() => {
        if((currentPages > 0) && (sort.status !== undefined)){
            getOrder()
        }
    }, [currentPages, sort])

    const getOrder = () => {
        const url = process.env.NEXT_PUBLIC_BACKEND + '/user/getOrder?sort=' + sort.status + '&pages=' + currentPages
        axios.get(url, {
            headers: { jwt: localStorage.getItem('jwt')}
        })
        .then(result => {
            setOrderList(result.data)
        })
    }

    const setStatusSort = (e) => {
        switch(e){
            case 'all': setSort({status: e, thai_status: 'ทั้งหมด'}); break;
            case 'ordered': setSort({status: e, thai_status: 'รอการชำระเงิน'}); break;
            case 'paid': setSort({status: e, thai_status: 'ชำระเงินแล้ว'}); break;
            case 'delivered': setSort({status: e, thai_status: 'จัดส่งแล้ว'}); break;
            case 'cancel': setSort({status: e, thai_status: 'ยกเลิก'}); break;
            default: setSort({status: 'all', thai_status: 'ทั้งหมด'})
        }
    }

    const nextPaidOrders = () => {
        if(orderList.length === 10){
            router.query.pages = currentPages + 1
            setCurrentPages(c => c+1)
            router.push({pathname: '/user/orders', query:{ ...router.query } }, undefined,{ shallow: true } )
        }
    }
    const previousPaidOrders = () => {
        if(orderList.length === 0) {
            router.query.pages = 1
            setCurrentPages(1)
            router.push({pathname: '/user/orders', query:{ ...router.query } }, undefined,{ shallow: true } )
            return
        }
        else if(currentPages > 1){
            router.query.pages = currentPages - 1
            setCurrentPages(c => c-1)
            router.push({pathname: '/user/orders', query:{ ...router.query } }, undefined,{ shallow: true } )
        }
    }

    const dropdownHandle = (e) => {
        if(e !== previousSort.status){
            setPreviousSort(sort)
            setStatusSort(e)
            setCurrentPages(1)
            router.query.sort = e
            router.push({pathname: '/user/orders', query:{ ...router.query } }, undefined,{ shallow: true } )
        }
        setShowDropdown(false)
    }


    if(!isLogin) {
        return (
            <div>
                <Head>
                    <title>Orders | PT Bookstore</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header />
                <div className={styles.container}>
                    <main className={styles.main}>
                        
                    </main>
                </div>
            </div>
        )
    } else {
        return (
            <div>
                <Head>
                    <title>Orders | PT Bookstore</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header />
                <div className={styles.container}>
                    <main className={styles.main}>
                        <SideNavBar />
                        <div className={styles.screen} >
                            <center><div className={styles.title}>รายการสั่งซื้อ</div></center>
                            <div>
                            <div className={styles.orderList}>
                            <div className={styles.flexEnd}>
                                <div className={`${styles.dropdownGroup} ${showDropdown? styles.showDropdown:''}`}>
                                    <div className={styles.dropdownSelection} onClick={e => {setShowDropdown(!showDropdown)}}>{sort.thai_status} <RiArrowDownSLine/></div>
                                    <div className={styles.dropdownList}>
                                        <div className={styles.dropdownItem} onClick={() => dropdownHandle('all')}>ทั้งหมด</div>
                                        <div className={styles.dropdownItem} onClick={() => dropdownHandle('ordered')}>รอการชำระเงิน</div>
                                        <div className={styles.dropdownItem} onClick={() => dropdownHandle('paid')}>ชำระเงินแล้ว</div>
                                        <div className={styles.dropdownItem} onClick={() => dropdownHandle('delivered')}>จัดส่งแล้ว</div>
                                        <div className={styles.dropdownItem} onClick={() => dropdownHandle('cancel')}>ยกเลิก</div>
                                    </div>
                                </div>
                            </div>
                            <div className={styles.itemHeader}>
                                <div className={styles.itemDetails}>OrderId</div>
                                <div className={styles.itemDetails}>วันที่</div>
                                <div className={styles.itemDetails}>ช่องทางชำระเงิน</div>
                                <div className={styles.itemDetails}>สถานะ</div>
                            </div>
                            {
                                orderList.map((element, index) => {
                                    var time = element.date
                                    time = time.replaceAll('.','/')
                                    return (
                                        <Link href={`/user/orders/${element.orderId}`} key={`order-${index}`}><a className={styles.item}>
                                            <div className={styles.itemDetails}>{element.orderId}</div>
                                            <div className={styles.itemDetails}>{time}</div>
                                            <div className={styles.itemDetails}>{element.method}</div>
                                            <div className={styles.itemDetails} style={{display: 'flex'}}>
                                                { element.status === 'ordered' && <div className={styles.status_gray}></div> }
                                                { element.status === 'paid' && <div className={styles.status_orange}></div> }
                                                { element.status === 'delivered' && <div className={styles.status_green}></div> }
                                                { element.status === 'cancel' && <div className={styles.status_red}></div> }
                                                { element.status }
                                            </div>
                                        </a></Link>
                                    )
                                })
                            }
                        </div>
                        <div className={styles.btnGroup}>
                            <div className={styles.btn} onClick={() => previousPaidOrders()}><IoIosArrowBack /></div>
                            {currentPages}
                            <div className={styles.btn} onClick={() => nextPaidOrders()}><IoIosArrowForward /></div>
                        </div>
                            </div>
                        </div>
                    </main>
                </div>
            </div>
        )
    }
}