import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import styles from './user.module.css'
import Header from 'components/header'
import axios from 'axios'

export default function User() {
    const [ isLogin, setIsLogin ] = useState(false)
    const router = useRouter()

    useEffect(() => {
        if(localStorage.getItem('jwt')){
            setIsLogin(true)
        } else {
            router.push({pathname: '/', query:{ } }, undefined,{ shallow: false } )
        }
    }, [])

    if(!isLogin) {
        return (
            <div>
                <Head>
                    <title>PT Bookstore</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header />
                <div className={styles.container}>
                    <main className={styles.main}>
                        
                    </main>
                </div>
            </div>
        )
    } else {
        return (
            <div>
                <Head>
                    <title>PT Bookstore</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header />
                <div className={styles.container}>
                    <main className={styles.main}>
                        Login
                    </main>
                </div>
            </div>
        )
    }
}