import { useState, useEffect, useContext } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Link from 'next/link'
import axios from 'axios'
import Image from 'next/image'
import styles from '../styles/Signin.module.css'

import { FaRegEnvelope, FaLock, FaLongArrowAltRight, FaChevronLeft } from 'react-icons/fa'

const SignIn = () => {

    const signInRequest = async(event) => {
        event.preventDefault()
        const url = process.env.NEXT_PUBLIC_BACKEND + '/auth/signIn';

        axios.post(url, {
            user: event.target.User.value,
            password: event.target.Password.value
        }).then((response) => {
            console.log(response.data)
            localStorage.setItem('jwt', response.data.token)
            localStorage.setItem('displayName', response.data.name)
            localStorage.setItem('userImg', response.data.img || '/no_profile_image.png')
            localStorage.setItem('userId', response.data.userId)
            router.push('/')
        }).catch((error) => {
            // password not match
            console.log(error);
        })
    }
    // redirect to home if already logged in
    const router = useRouter()
    const [ loadDone, setLoadDone ] = useState(false)

    useEffect(()=> {
        if(router.isReady){
            if(localStorage.getItem('jwt') || 0){
                router.push('/')
            } else {
                setLoadDone(true)
            }
        }
    }, [router])
    
    if(!loadDone){
        return (
            <div>
                <Head>
                    <title>Sign In | PT Bookstore</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
            </div>
        )
    } else {
        return (
            <div className={styles.limiter}>
                <Head>
                    <title>Sign In | PT Bookstore</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className={styles.containerLogin}>
                    <div className={styles.wrapLogin}>
                        <div className={styles.containerBackBtn}>
                            <Link href='../'>
                                <a><span className={styles.backIcon}>
                                    <FaChevronLeft />
                                    <span className={styles.tooltip}>Back</span>
                                </span></a>
                            </Link>
                        </div>

                        <form className={styles.loginForm} onSubmit={signInRequest}>
                            <span className={styles.loginFormTitle}>
                                Member Login
                            </span>

                            <div className={styles.wrapInput}>
                                <input className={styles.input} type='text' id='User' name='User' placeholder='Email or Phone'></input>
                                <span className={styles.focusInput}></span>
                                <span className={styles.iconInput}>
                                    <i><FaRegEnvelope /></i>
                                </span>
                            </div>

                            <div className={styles.wrapInput}>
                                <input className={styles.input} type='password' id='Password' name='Password' placeholder='Password'></input>
                                <span className={styles.focusInput}></span>
                                <span className={styles.iconInput}>
                                    <i><FaLock /></i>
                                </span>
                            </div>

                            <div className={styles.containerBtn}>
                                <button className={styles.btn}>
                                    Login
                                </button>
                            </div>

                            <div className={styles.textCenter}>
                                <span className={styles.txt1}>
                                    Forget
                                </span>
                                <span className={styles.txt1Link}>
                                    <Link href='#'>
                                        <a>Username / Password?</a>
                                    </Link>
                                </span>
                            </div>

                            <div className={styles.textBottom}>
                                <Link href='/signup'>
                                    <a><span className={styles.txt2}>
                                        Create your Account
                                        <i><FaLongArrowAltRight /></i>
                                    </span></a>
                                </Link>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        )
    }
}

export default SignIn